tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-background": "#1c171a",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed-variant": "#223b34",
                "secondary-fixed": "#dbebe6",
                "on-primary-fixed": "#3a0022",
                "inverse-on-surface": "#faf7f2",
                "outline": "#8c7781",
                "surface-container-lowest": "#ffffff",
                "on-surface-variant": "#62505b",
                "tertiary-container": "#fce8ee",
                "primary-container": "#fce8ee",
                "on-primary-fixed-variant": "#6a254c",
                "primary-fixed": "#ffd8ec",
                "surface-container-low": "#faf5f8",
                "surface-container-highest": "#f2eaef",
                "on-secondary-container": "#243c35",
                "secondary-container": "#dbebe6",
                "on-tertiary-container": "#523c4f",
                "on-primary": "#ffffff",
                "tertiary-fixed-dim": "#f7d9f2",
                "on-tertiary-fixed": "#2d162b",
                "surface-dim": "#ece5e9",
                "tertiary-fixed": "#fcdcf7",
                "on-tertiary-fixed-variant": "#5a4156",
                "primary-fixed-dim": "#fdb2de",
                "surface-variant": "#f2eaef",
                "on-primary-container": "#4f082f",
                "on-error": "#ffffff",
                "inverse-primary": "#fdb2de",
                "error": "#ba1a1a",
                "secondary-fixed-dim": "#a2c1b7",
                "surface-bright": "#fcf9f5",
                "inverse-surface": "#342e31",
                "on-surface": "#1c171a",
                "primary": "#9b1e63",
                "on-error-container": "#93000a",
                "surface-container-high": "#ebe3e7",
                "on-secondary-fixed": "#10231e",
                "background": "#fcf9f5",
                "surface-tint": "#9b1e63",
                "on-secondary": "#ffffff",
                "secondary": "#5a7a71",
                "outline-variant": "#e5d9df",
                "error-container": "#ffdad6",
                "surface": "#fcf9f5",
                "surface-container": "#f2eaef",
                "tertiary": "#8e758c"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-desktop": "80px",
                "stack-sm": "8px",
                "gutter": "24px",
                "section-gap": "120px",
                "stack-md": "16px",
                "stack-lg": "32px",
                "margin-mobile": "20px"
            },
            "fontFamily": {
                "display-lg": ["Playfair Display"],
                "headline-md": ["Playfair Display"],
                "headline-sm": ["Playfair Display"],
                "price-display": ["Playfair Display"],
                "body-lg": ["DM Sans"],
                "display-lg-mobile": ["Playfair Display"],
                "label-caps": ["DM Sans"],
                "body-md": ["DM Sans"]
            },
            "fontSize": {
                "display-lg": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
                "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }],
                "price-display": ["20px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "label-caps": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "700" }],
                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
            }
        },
    },
};
